config/routes.rb
Rails.application.routes.draw do

    root 'root_pages#home'

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :articles
  resource :cart, only: [:show]
  resources :orders
  get 'deliver_order', to: 'orders#deliver_order'
  resources :order_items, only: [:create, :update, :destroy]

  resources :articles do
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
  end

  get 'bestellen', to: 'articles#bestellen'
  get 'confirm_order', to: 'carts#confirm_order'
  post 'confirm_order_details', to: 'carts#confirm_order_details'
  get 'cancel_order',  to: 'carts#cancel_order'
  get 'meine_bestellungen', to: 'orders#user_orders'
  get 'received_order', to: 'orders#received_order'
  get 'profile_edit', to: 'users#profile_edit'

end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_votable
  belongs_to :order
  belongs_to :category
  has_many :order_items
  mount_uploader :img_name, PictureUploader

  scope :filter, ->(id){where('category_id = ?', id) if id.present?}

  validates :name, presence: true
  validates :price, :format => { :with => /\A\d+(?:\.\d{0,2})?\z/ },
    :numericality => {:greater_than => 0, :less_than => 1000}
  validates :description, presence: true
  validates :category_id, presence: true
  validate :picture_size

  private

    # Validates the size of an uploaded picture.
    def picture_size
      if img_name.size > 5.megabytes
        errors.add(:img_name, "should be less than 5MB")
      end
    end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action only: [:index, :new, :create, :edit, :update, :destroy, :show] do
    allow_only_admin(bestellen_path)
  end
  before_action  only: [:bestellen] do
    allow_only_normal_user(articles_path)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def index
    applyAttributes

  end

  def bestellen 
    applyAttributes
  end 

  def show
    @article = Article.find(params[:id])
    @order_item = current_order.order_items.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    redirect_to articles_path()
  end

  # upvote with help of acts_as_votable
  def upvote
    @article = Article.find(params[:id])
    @article.liked_by current_user
    redirect_to article_path
  end

  def downvote
    @article = Article.find(params[:id])
    @article.downvote_by current_user
    redirect_to article_path
  end

  private

    def article_params
      params.require(:article).permit(:name, :description, :price, :isVegetarian, :category_id, :img_name)
    end

    def applyAttributes  
      @categories = Category.all
      @articles = Article.filter(params[:filter]).paginate(:page => params[:page], :per_page => 10)
      @order_item = current_order.order_items.new
    end 
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div class="form-group">
  <%= f.label :name, 'Name' %>
  <%= f.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :description, 'Beschreibung' %>
  <%= f.text_area :description, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :price, 'Preis' %>
  <%= f.text_field :price, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.check_box :isVegetarian %>
  <%= f.label :isVegetarian, " vegetarisch" %>
</div>

app/views/articles/bestellen.html.erb
<div class="btn-group category-btns">
	<%= link_to "Alle", bestellen_path, class: "btn btn-default" %>
	<% @categories.each do |category| %>
	<%= link_to category.name, bestellen_path(filter: category.id), class: "btn btn-default category-btn" %>
	<% end %>
</div>

<ul class="articles">

	<% @articles.each do |article| %>
	<li>

		<div class = "col-md-2" >
			<%= image_tag(article.img_name, class: "food-img", :size => "140x140") if article.img_name? %>
		</div>
		<div class = "col-md-6">
			<p><%=link_to article.name, article %></p>
			<p class="small"><%= article.category.name %></p>
			<p><%=article.description.truncate_words(22) %></p>
		</div>

		<div class = "col-md-4" >

			<%= form_for @order_item, remote: true do |f| %>

			<div class = "col-md-4 col-md-offset-3">
				<%= f.number_field :quantity, value: 1, class: "form-control", min: 1, :id => "#{article.name}-quantity" %>
			</div>

			<div class = "col-md-4">
				<%= f.hidden_field :article_id, value: article.id %>
				<%= article.price %> €
				<%= button_tag(type: 'submit', class: "btn btn-primary cart-btn", :id =>  "#{article.name}-cart-button") do %>
				<i class="glyphicon glyphicon-shopping-cart"></i>
				<% end %>
			</div>
			<% end %>

		</div>
	</li>
	<% end %>
</ul>
<%= will_paginate :previous_label => "Zurück", :next_label => "Weiter" %>

app/views/articles/edit.html.erb
<div class="col-md-4 center-div">
  <h1>Edit Article</h1>

  <%= form_for(@article) do |f| %>

    <%= f.select :category_id, Category.all.map{|c| [c.name, "#{c.id}"]} %>


    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.check_box :isVegetarian %>
      <%= f.label :isVegetarian, " vegetarisch" %>
    </div>

    <%= f.file_field :img_name, accept: 'image/jpeg,image/gif,image/png' %>

    <%= f.submit "Speichern", class: "btn btn-primary pull-right" %>

  <% end %>

  <%= link_to "Artikel Löschen", @article, method: :delete,
    data: { confirm: "Artikel #{@article.name} löschen?" }, :class => "btn btn-danger" %>
  <br/>
  <br/>
  <%= link_to "Abbrechen", :back, class: "btn btn-default" %>
</div>

app/views/articles/index.html.erb
<div class="btn-group category-btns">
  <%= link_to "Alle", articles_path, class: "btn btn-default" %>
  <% @categories.each do |category| %>
  <%= link_to category.name, articles_path(filter: category.id), class: "btn btn-default category-btn" %>
  <% end %>
</div>


<% if current_user.try(:admin?) %>
<%= link_to new_article_path, :class => "btn btn-success pull-right" do %>
<i class="glyphicon glyphicon-plus"></i>
<% end %>
<% end %>

<ul class="articles">

  <% @articles.each do |article| %>
  <li>

    <div class = "col-md-2" >
      <%= image_tag(article.img_name, class: "food-img", :size => "140x140") if article.img_name? %>
    </div>
    <div class = "col-md-5">
      <p><%=link_to article.name, article %></p>
      <p class="small"><%= article.category.name %></p>
      <p><%=article.description.truncate_words(22) %></p>
    </div>

    <div class = "col-md-5" >

     <div class="col-md-2">
      <%= link_to edit_article_path(article), :class => "btn btn-warning cart-btn" do %>
      <i class="glyphicon glyphicon-edit"></i>
      <% end %>

      <%= link_to article, method: :delete,
      data: { confirm: "Artikel #{article.name} löschen?" }, id: 'destroy', :class => "btn btn-danger cart-btn" do %>
      <i class="glyphicon glyphicon-remove"></i>
      <% end %>
    </div>

  </div>
</li>
<% end %>
</ul>
<%= will_paginate :previous_label => "Zurück", :next_label => "Weiter" %>

app/views/articles/new.html.erb
<div class="col-md-4 center-div">
  <h1>Create new Article</h1>
  <%= form_for(@article, html: { multipart: true }) do |f| %>

    <%= f.select :category_id, Category.all.map{|c| [c.name, "#{c.id}"]} %>

    <div class="form-group">
      <%= f.label :name, 'Name' %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Beschreibung / Zutaten" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.check_box :isVegetarian %>
      <%= f.label :isVegetarian, " vegetarisch" %>
    </div>

    <%= f.file_field :img_name, accept: 'image/jpeg,image/gif,image/png' %>

    <%= link_to "Abbrechen", :back, class: "btn btn-default" %>
    <%= f.submit "Erstellen", class: "btn btn-primary pull-right" %>

  <% end %>

</div>

<script type="text/javascript">
  $('#article_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/articles/show.html.erb
<div class="container">

  <div class="col-md-12 article-detail">
    <%= image_tag(@article.img_name, class: "food-img", :size => "140x140") if @article.img_name? %>
    <h1> <%= @article.name %> <br/><small><%= @article.category.name%></small></h1>
    <p> <%= @article.description %></p>
  </div>

  <div>

    <div class="col-md-6">

      <% if !current_user.try(:admin?) %>

      <div class="btn-group">

        <%= link_to like_article_path(@article), method: :put, :class => "btn btn-success" do %>
        <i class="glyphicon glyphicon-heart"></i>
        <% end %>

        <%= link_to dislike_article_path(@article), method: :put, :class => "btn btn-danger" do %>
        <i class="glyphicon glyphicon-heart-empty"></i>
        <% end %>

      </div>

      <% end %>
      <small>
        <% @likes = @article.get_likes.size %>

        <% if @likes < 0 %>
          Dieses Essen schmeckt nicht.
        <% elsif @likes == 0 %> 
          Dieses Essen hat noch niemand bewertet, sei der Erste! 
        <% elsif @likes > 1 %> 
          <%= @likes %> Nutzer finden diese Speise lecker.
        <% else %> 
          <%= @likes %> Nutzer findet diese Speise lecker.
        <% end %> 
      </small>
    </div>

    <div class="col-md-2">

      <% if current_user.try(:admin?) %>

      <%= link_to edit_article_path(@article), :class => "btn btn-warning cart-btn" do %>
      <i class="glyphicon glyphicon-edit"></i>
      <% end %>

      <%= link_to @article, method: :delete,
      data: { confirm: "Artikel #{@article.name} löschen?" }, :class => "btn btn-danger cart-btn" do %>
      <i class="glyphicon glyphicon-remove"></i>
      <% end %>

      <% end %>

    </div>

    <div class="col-md-4">
      <% if !current_user.try(:admin?) %>
        <%= form_for @order_item, remote: true do |f| %>

        <div class = "col-md-4 col-md-offset-3">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
        </div>

        <div class = "col-md-5">
          <%= f.hidden_field :article_id, value: @article.id %>
          <%= @article.price %> €

          <%= button_tag(type: 'submit', class: "btn btn-primary cart-btn") do %>
          <i class="glyphicon glyphicon-shopping-cart"></i>
          <% end %>

        </div>

        <% end %>
      <% end %>
    </div>

  </div>


</div>