config/routes.rb
Rails.application.routes.draw do

    root 'root_pages#home'

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :articles
  resource :cart, only: [:show]
  resources :orders
  get 'deliver_order', to: 'orders#deliver_order'
  resources :order_items, only: [:create, :update, :destroy]

  resources :articles do
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
  end

  get 'bestellen', to: 'articles#bestellen'
  get 'confirm_order', to: 'carts#confirm_order'
  post 'confirm_order_details', to: 'carts#confirm_order_details'
  get 'cancel_order',  to: 'carts#cancel_order'
  get 'meine_bestellungen', to: 'orders#user_orders'
  get 'received_order', to: 'orders#received_order'
  get 'profile_edit', to: 'users#profile_edit'

end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  before_save :update_subtotal

  enum order_status: ['Erstellung','Auftrag','Abgeschickt','Angekommen','Storniert' ]
  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0}.sum
  end

  def count
    order_items.collect { |i| i.valid? ? (i.quantity) : 0}.sum
  end

  private
    def update_subtotal
      self[:subtotal] = subtotal
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :allow_only_admin, only: [:index, :deliver_order, :destroy]
  before_action only: [:user_orders, :received_orders] do
    allow_only_normal_user(orders_path)
  end
  before_action :is_there_user, only: [:user_orders]
  before_action :is_correct_user, only: [:show]

  def index
    @orders = Order.all
    @orders.each do |order|
      if order.Erstellung? && (order.updated_at < 2.hours.ago)
        Order.find(order[:id]).destroy
      end
    end
  end

  def destroy
    Order.find(params[:id]).destroy
    redirect_to orders_path
  end

  def show
    @order = Order.find(params[:id])
  end

  def deliver_order
    @order = Order.find(params[:order_id])
    @order.Abgeschickt!
    @order.save
    redirect_to orders_path
  end

  def received_order
    @order = Order.find(params[:order_id])
    @order.Angekommen!
    @order.save
    redirect_to meine_bestellungen_path
  end

  def user_orders
    @orders = Order.where(user_id: current_user[:id])
    
  end

  private

    def allow_only_admin
      if user_signed_in?
        if (!current_user.try(:admin?))
          redirect_to(meine_bestellungen_path)
        end
      else
	  redirect_to(bestellen_path)
      end
    end

    def is_there_user
      if !(user_signed_in?) 
        redirect_to(bestellen_path)
      end
    end

    def is_correct_user
      order = Order.find(params[:id])
      if (user_signed_in?)
        if ((current_user[:id] !=  order[:user_id]) && !(current_user.try(:admin?)))
          redirect_to(meine_bestellungen_path)
        end
      else
	 redirect_to(bestellen_path)
      end
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<div class="col-md-8 col-md-offset-2">
  <table class="table table-striped">
    <tr>
      <td>Info</td><td>Aktionen</td>
    </tr>
    <% @orders.each do |order| %>
    <% if !order.Erstellung? %>
        <tr>
          <td>
            Status: <%= order.order_status %> <br/>
            An: <%= order.street %> <br/>
            <%= order.postal %> <%= order.city %>
          </td>
          <td>
            <%= link_to order , method: :delete,
                  data: { confirm: "Bestellung löschen?" }, :class => "btn btn-danger cart-btn" do %>
                  <i class="glyphicon glyphicon-remove"></i>
            <% end %>
            <%= link_to "Details", order_path(order.id), :class => "btn btn-primary cart-btn" %>
            <% if order.Auftrag? %>
              <%= link_to "Liefern", deliver_order_path(:order_id => order.id), :class => "btn btn-success cart-btn" %>
            <% end %>


          </td>
        </tr>
      <% end %>
     <% end %>
  </table>



</div>

app/views/orders/show.html.erb
<div class="col-md-8 cold-md-offset-2">
  <table class="table table-striped">
    <tr>
      <td>#</td><td>Quantity</td><td>Name</td><td>Total Price</td>
    </tr>
    <% @order.order_items.each do |order_item| %>
    <tr>
	<td> # </td>
	<td><%= order_item.quantity %></td>
	<td><%= order_item.article.name %></td>
	<td><%= order_item.total_price %> €</td>
    </tr>
    <% end %>
  </table>
  <%= link_to "Zurück", :back, class: "btn btn-default" %>
</div>

app/views/orders/user_orders.html.erb
<div class="col-md-8 col-md-offset-2">
  <table class="table table-striped">
    <tr>
      <td>Info</td><td>Aktionen</td>
    </tr>
    <% if @orders.count > 0 %>
    <% @orders.each do |order| %>
      <% if !(order.Erstellung?) %>
        <tr>
          <td>
            Status: <%= order.order_status %> <br/>
            An: <%= order.street %> <br/>
            <%= order.postal %> <%= order.city %>
          </td>
	  <td>
	  <% if order.Auftrag? %>
		  <%= link_to "Stornieren", cancel_order_path(:order_id => order.id) , data: { confirm: "Bestellung stornieren?" }, :class => "btn btn-danger cart-btn" %>
          <% elsif order.Abgeschickt? %>
		  <%= link_to "Geliefert",  received_order_path(:order_id => order.id), :class => "btn btn-success cart-btn"%>
          <% end %>
            <%= link_to "Details", order_path(order.id), :class => "btn btn-primary cart-btn" %>

          </td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
  </table>



</div>