config/routes.rb
Rails.application.routes.draw do

    root 'root_pages#home'

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :articles
  resource :cart, only: [:show]
  resources :orders
  get 'deliver_order', to: 'orders#deliver_order'
  resources :order_items, only: [:create, :update, :destroy]

  resources :articles do
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
  end

  get 'bestellen', to: 'articles#bestellen'
  get 'confirm_order', to: 'carts#confirm_order'
  post 'confirm_order_details', to: 'carts#confirm_order_details'
  get 'cancel_order',  to: 'carts#cancel_order'
  get 'meine_bestellungen', to: 'orders#user_orders'
  get 'received_order', to: 'orders#received_order'
  get 'profile_edit', to: 'users#profile_edit'

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
    @order = current_order
  end

  def confirm_order
    @order = current_order
  end

  def confirm_order_details
    @order = current_order
    @order.street = params[:street]
    @order.postal = params[:postal]
    @order.city = params[:city]
    @order.Auftrag!;
    @order.save!
    @pay = params[:payment]
    #@order = Order.new.save!
  end

  def cancel_order
    @order = Order.find(params[:order_id])
      if (@order.Auftrag?)
        @order.Storniert!
        @order.save
      end
    redirect_to :back
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">
  <div class="row">
    <div class="col-xs-8">
      <h4> <%= article.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Einzelpreis: <span style="color: green"><%= order_item.unit_price %> €</span></h4>
        <div class="row">

          <div class="col-md-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1%>
            <%= f.hidden_field :article_id, value: article.id %>
          </div>

          <div class="col-md-8 text-right">

            <div class="btn-group">
              <%= f.submit "Anzahl ändern", class: "btn btn-primary" %>
              <%= link_to "Löschen", order_item, { data: {confirm: "Are you sure you wish to delete the product '#{order_item.article.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>

          </div>

        </div>
        <h4 class="text-right">Gesamtpreis: <span style="color: green"><%=order_item.total_price %> €</span></h4>
      <% end %>
    </div>
  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @order_item.errors.full_messages.each do |msg| %>
        <li><%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    Warenkorb leer. <%= link_to "Hier", articles_path %> Artikel hinzufügen.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', article: order_item.article, order_item: order_item, show_total: true %>
  <% end %>
<% end %>
<div>
  <% if @order_items.try(:count) > 0 %>
    <% if current_order.Erstellung? %>

      <%= link_to confirm_order_path, :class => "btn btn-success cart-btn pull-right" do %>
        <i class="glyphicon glyphicon-ok"> Bestellen</i>
      <% end %>

    <% elsif current_order.Auftrag?  %>

      <%= link_to cancel_order_path, data: { confirm: "Bestellung stornieren?" },
        :class => "btn btn-danger cart-btn pull-right" do %>
        <i class="glyphicon glyphicon-ok"> Stornieren</i>
      <% end %>
    <% end %>
  <% end %>
</div>
          Status: <%= current_order.order_status %>

app/views/carts/confirm_order.html.erb
<h1>Bestellung bestätigen</h1>
<h2>Lieferadresse</h1>

<%= form_tag confirm_order_details_path do %>
  <div class="form-group col-md-12">
    <%= label_tag 'Straße & Hausnummer' %>
    <%= text_field_tag(:street, (current_user.street if current_user), class: "form-control") %>
  </div>

  <div class="form-group col-md-2">
    <%= label_tag 'PLZ' %>
    <%= text_field_tag(:postal, (current_user.postal if current_user), class: "form-control") %>
  </div>

  <div class="form-group col-md-10">
    <%= label_tag 'Ort' %>
    <%= text_field_tag(:city, (current_user.city if current_user), class: "form-control") %>
  </div>

  <h2>Bezahl-Methode</h2>
  <div class="form-group col-md-10">
    <%= radio_button_tag :payment, "cash", true %>
    <%= label_tag :payment_cash, "Bar bei Lieferung" %>
    <br/>
    <%= radio_button_tag :payment, "credit" %>
    <%= label_tag :payment_credit, "Kreditkarte" %>
  </div>

  <%= button_tag(type: "submit", class: "btn btn-success") do %>
    <i class="glyphicon glyphicon-ok"> Bestellen</i>
  <% end %>


<% end %>

app/views/carts/confirm_order_details.html.erb
<h1>Ihre Bestellung wurde in Auftrag gegeben.</h1>
<%= "#{@pay}" %>
<%= "#{current_order.order_status}" %>

app/views/carts/okay.html.erb
<h1>Bestellung bestätigen</h1>
<h2>Liefer-Adresse</h2>
<%= form_tag okay_okay_path do %>
  <div class="form-group col-md-12">
    <%= label_tag 'Straße & Hausnummer' %>
    <%= text_field_tag(@street, (current_user.street if current_user), class: "form-control") %>
  </div>

  <div class="form-group col-md-2">
    <%= label_tag 'PLZ' %>
    <%= text_field_tag(@postal, (current_user.postal if current_user), class: "form-control") %>
  </div>

  <div class="form-group col-md-10">
    <%= label_tag 'Ort' %>
    <%= text_field_tag(@city, (current_user.city if current_user), class: "form-control") %>
  </div>

  <h2>Bezahl-Methode</h2>
  <div class="form-group col-md-10">
    <%= radio_button_tag :payment, "cash", true %>
    <%= label_tag :payment_cash, "Bar bei Lierferung" %>
    <br/>
    <%= radio_button_tag :payment, "credit" %>
    <%= label_tag :payment_credit, "Kreditkarte" %>
  </div>

  <%= button_tag(type: "submit", class: "btn btn-success") do %>
    <i class="glyphicon glyphicon-ok"> Bestellen</i>
  <% end %>


<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>