config/routes.rb
Rails.application.routes.draw do

    root 'root_pages#home'

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update, :destroy]
  resources :articles
  resource :cart, only: [:show]
  resources :orders
  get 'deliver_order', to: 'orders#deliver_order'
  resources :order_items, only: [:create, :update, :destroy]

  resources :articles do
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
  end

  get 'bestellen', to: 'articles#bestellen'
  get 'confirm_order', to: 'carts#confirm_order'
  post 'confirm_order_details', to: 'carts#confirm_order_details'
  get 'cancel_order',  to: 'carts#cancel_order'
  get 'meine_bestellungen', to: 'orders#user_orders'
  get 'received_order', to: 'orders#received_order'
  get 'profile_edit', to: 'users#profile_edit'

end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.count} in Warenkorb ( #{current_order.subtotal} €)", cart_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<hr/>
<small class='pull-right footer-txt'>Foodle 2015</small>

app/views/layouts/_header.html.erb
<%= nav_bar fixed: :top, responsive: true do %>
  <%= menu_group do %>
    <% if current_user.try(:admin?) %>
      <%= menu_item "Stammdaten", articles_path %>
      <%= menu_item "Benutzer", users_path %>
      <%= menu_item "Bestellungen", orders_path %>
    <% else %>
      <%= menu_item "Foodle", root_path %>
      <%= menu_item "Bestellen", bestellen_path %>
      <% if current_user %>
        <%= menu_item "Meine Bestellungen", meine_bestellungen_path %>
      <% end %>
    <% end %>
  <% end %>

  <%= menu_group :pull => :right do %>
  <% if current_user.try(:admin?) %>
    <%= menu_item "(Admin)" %>
  <% end %>
      <% if current_user %>
        <%= drop_down "Account" do %>
            <%= menu_item "Profil bearbeiten", profile_edit_path %>
            <%= menu_item "Passwort ändern", edit_user_registration_path(current_user) %>
            <%= menu_item "Abmelden", destroy_user_session_path, method: :delete %>
        <% end %>
      <% else %>
          <%= menu_item "Anmelden", new_user_session_path %>
          <%= menu_item "Registrieren", new_user_registration_path %>
      <% end %>
  <% end %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert ">
    <a href="#" data-dismiss="alert" class="close">×</a>
      <ul>
        <li>
          <%= value %>
        </li>
      </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <%= render 'layouts/messages'%>
    <div class="text-right">
      <% if !(current_user.try(:admin?)) %>
        <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
      <% end %>
    </div>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

</body>
</html>